spring:
  kafka:
    client-id: word-count
    bootstrap-servers:
      - localhost:9095
      - localhost:9096

    template:
      default-topic: word_topic
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.LongSerializer
#    consumer:
#      group-id: random-consumer
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
---
kafka:
  topic:
    input: word_topic
    #even-output: square-output
